version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: smart-tourism-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  app:
    build: .
    container_name: smart-tourism-app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:secret@mongo:27017/smart-tourism?authSource=admin"
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data:
  mongo-config: