name: DevSecOps Orchestrator

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  security-events: write 

jobs:
  trufflehog:
    uses: ./.github/workflows/trufflehog.yml
    
  snyk:
    uses: ./.github/workflows/snyk.yml

  # semgrep:
  #   uses: ./.github/workflows/semgrep.yml

  # sonarqube:
  #   needs: trufflehog
  #   uses: ./.github/workflows/sonarqube.yml

  # zap:
  #   uses: ./.github/workflows/zap.yml

  # sqlmap:
  #   uses: ./.github/workflows/sqlmap.yml

  # nmap:
  #   uses: ./.github/workflows/nmap.yml