name: Nmap Security Scan

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose services
        run: |
          docker-compose up -d
          sleep 30  # Περίμενε λίγο για να ξεκινήσουν τα containers (προσαρμοσμένο ανάλογα με την app σου)

      - name: Scan with Nmap
        uses: thereisnotime/action-nmap@v1  # Χρησιμοποίησε stable version tag
        with:
          target: "localhost"  # Σκανάρει το local app service
          additional_args: "-oA report -p 5000 -sV -sC -A -T4 -v"  # Παράδειγμα args: Σκανάρει port 5000, service versions, scripts για vulns, aggressive scan

      - name: Upload Nmap report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nmap-report
          path: report.*  # XML, normal, grepable reports από Nmap

      - name: Stop Docker Compose services
        if: always()  # Πάντα stop, ακόμα και αν fail-άρει
        run: docker-compose down