name: Nmap Security Scan

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start stack with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for services to start
        run: |
          echo "Waiting for app to be ready..."
          sleep 30
          docker ps

      - name: Check logs (debugging)
        run: docker logs smart-tourism-app || true

      - name: Test app with curl
        run: |
          curl --retry 10 --retry-delay 5 --fail http://localhost:5000 || (docker logs smart-tourism-app && exit 1)

      - name: Stop stack
        if: always()
        run: docker compose -f docker-compose.yml down