name: Nmap Security Scan

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for app to be ready
        run: |
          echo "Waiting for app to start..."
          for i in {1..15}; do
            if curl -s http://localhost:5000 >/dev/null; then
              echo "App is up!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 5
          done
          echo "App did not start in time" >&2
          docker compose logs
          exit 1

      - name: Run Nmap scan
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap
          nmap -p 5000 localhost

      - name: Stop services
        run: docker compose -f docker-compose.yml down
