name: DevSecOps - TruffleHog

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          base: ${{ github.event.pull_request && github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request && github.event.pull_request.head.sha || github.sha }}
          extra_args: --results=verified

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
